### ISSUE TITLE
cut with solid from parametricCurve

### ISSUE THREAD

**Issue by asprionj** [CadQuery/cadquery#260] opened 2019-12-28 23:20 UTC
(I'm on 2.0RC1.) Trying to cut a body that is constructed by revolving a `parametricCurve` from another body. For illustration, a minimal example which is working as expected, but using a `circle` instead of said `parametricCurve`:

```python
s = cq.Workplane('XY').circle(50).extrude(20) # the base body
to_cut = cq.Workplane('XY').transformed(offset=[35,0,0], rotate=[90,0,0]).circle(14).revolve(315, [-35,0,0], [-35,1,0]) # this will be cut away
s = s.cut(to_cut) # cut it...
```

The result looks fine (I cannot fully close the torus because of #259):
![image](https://user-images.githubusercontent.com/13935112/71550397-a9164700-29cf-11ea-8096-b6fc2434cc86.png)

Now, if I use a `parametricCurve`, e.g. to have an ellipse instead of a circle (or any other complex geometry):

```python
from math import sin, cos, pi

def my_ellipse(t, a, b):
    return (a*sin(2*pi*t), b*cos(2*pi*t))

to_cut = cq.Workplane('XY').transformed(offset=[35,0,0], rotate=[90,0,0]).parametricCurve(lambda t: my_ellipse(t,14,7)).revolve(315, [-35,0,0], [-35,1,0])
``` 
it fails with "**RuntimeError**: Standard_Failure Courbes non jointives". (Also when using `intersect` instead of `cut`.)

Funny thing is, if I use `union` instead of `cut`, it does work as expected:
![image](https://user-images.githubusercontent.com/13935112/71550436-7456bf80-29d0-11ea-9a12-e8c9e473e193.png)

**Comment by adam-urbanczyk** [comment] 2019-12-29 00:01
Confirmed, looks like a cad kernel issue. Same workaround as in #259 :
```python
from math import sin, cos, pi

def my_ellipse(t, a, b):
    return (a*sin(2*pi*t), b*cos(2*pi*t))

to_cut = cq.Workplane('XY').transformed(offset=[35,0,0], rotate=[90,0,0]).parametricCurve(lambda t: my_ellipse(t,14,7)).revolve(360, [-35,0,0], [-35,1,0],clean=False)

s = cq.Workplane('XY').circle(50).extrude(20)
s = s.cut(to_cut,clean=False)

show_object(s)
```
![afbeelding](https://user-images.githubusercontent.com/13981538/71550670-b3880f00-29d6-11ea-8d11-802c3d8aa2ce.png)

**Comment by lorenzncode** [comment] 2022-09-23 01:37
Fixed in occt7.6 branch.

```py
from math import sin, cos, pi

def my_ellipse(t, a, b):
    return (a*sin(2*pi*t), b*cos(2*pi*t))

s = cq.Workplane('XY').circle(50).extrude(20) # the base body
to_cut = cq.Workplane('XY').transformed(offset=[35,0,0], rotate=[90,0,0]).parametricCurve(lambda t: my_ellipse(t,14,7)).revolve(315, [-35,0,0], [-35,1,0])
s = s.cut(to_cut)

print(s.val().isValid())
```
occt7.6:
![image](https://user-images.githubusercontent.com/16394272/191877726-886882e9-e904-4887-ab60-01924c12cbc1.png)

current master (ocp-7.5.3):
![image](https://user-images.githubusercontent.com/16394272/191877773-6c5155fe-d887-4c8c-9137-9d3f4f0af2b9.png)

**Comment by adam-urbanczyk** [comment] 2022-09-23 05:25
Thanks @lorenzncode for checking - I'm adding this issue to the PR.

**Closed** 2022-10-01 07:31 UTC
Labels: bug, OCC kernel issue
