### ISSUE TITLE
Exported GLTF file is broken

### ISSUE THREAD

**Issue by roipoussiere** [CadQuery/cadquery#1154] opened 2022-09-14 07:15 UTC
I try to export a simple gltf file of an assembly:
```py
box = cq.Workplane().box(1, 2, 3)
asm = cq.Assembly().add(box)
cq.Assembly().add(box).save('box.gltf')
```

The script outputs:

    RWGltf_CafWriter skipped node 'c44caed6-33fd-11ed-94b0-bf8faf8ebb27_part' without triangulation data

And the file seems broken. When I try to import it:
- in [this gltf web viewer](https://gltf.insimo.com/), it fails with the error `i is undefined`;
- in [this other viewer](https://playcanvas.com/viewer), it fails with unknown error;
- in [this other viewer](https://sandbox.babylonjs.com/), it fails with a json parsing error,
- with Blender, it doesn't fail but the model doesn't appear in the scene (only in the tree view).

Same errors if I set the output format explicitly with `exportType='GLTF'`.

**Comment by lorenzncode** [comment] 2022-09-19 00:33
Duplicate of #993

**Closed** 2022-11-06 19:16 UTC
Labels: duplicate
