### ISSUE TITLE
How to create a engineering drawing?

### ISSUE THREAD

**Issue by kchbpy** [CadQuery/cadquery#210] opened 2019-11-13 14:29 UTC

**Comment by jmwright** [comment] 2019-11-13 18:14
@kchbpy CadQuery has the ability to export to the SVG format so you could probably create projections for views, but that's as close as you can get currently. There's no provision for complex 2D work or adding dimensions.

**Comment by adam-urbanczyk** [comment] 2019-11-13 19:04
@kchbpy this is a duplicate of #122

**Closed by adam-urbanczyk** 2019-11-13 19:04 UTC
